// Create Web Server with Express
// 1. npm init -y
// 2. npm install express
// 3. npm install --save-dev nodemon
// 4. npm install dotenv
// 5. npm install mongoose
// 6. npm install bcrypt
// 7. npm install jsonwebtoken
// 8. npm install express-validator
// 9. npm install cookie-parser
// 10. npm install express-session
// 11. npm install connect-mongodb-session
// 12. npm install csurf
// 13. npm install connect-flash
// 14. npm install multer
// 15. npm install uuid
// 16. npm install nodemailer
// 17. npm install nodemailer-sendgrid-transport
// 18. npm install express-handlebars
// 19. npm install handlebars
// 20. npm install handlebars.moment
// 21. npm install moment
// 22. npm install @handlebars/allow-prototype-access
// 23. npm install helmet
// 24. npm install compression
// 25. npm install express-mysql-session
// 26. npm install mysql2
// 27. npm install sequelize
// 28. npm install express-session
// 29. npm install express-graphql
// 30. npm install graphql
// 31. npm install graphql-tools
// 32. npm install express-validator
// 33. npm install nodemailer
// 34. npm install nodemailer-sendgrid-transport
// 35. npm install bcrypt
// 36. npm install jsonwebtoken
// 37. npm install multer
// 38. npm install uuid
// 39. npm install csurf
// 40. npm install connect-flash
// 41. npm install express-handlebars
// 42. npm install handlebars
// 43. npm install handlebars.moment
// 44. npm install moment
// 45. npm install @handlebars/allow-prototype-access
// 46. npm install helmet
// 47. npm install compression
// 48. npm install express-mysql-session
// 49. npm install mysql2
// 50. npm install sequelize
// 51. npm install express-session
// 52. npm install express-validator
// 53. npm install graphql
// 54
